# The stanford_travisci_scripts repository contains external scripts
# used here to configure server and build a self-service site.
# https://github.com/SU-SWS/stanford_travisci_scripts

# PRODUCT_NAME:
# Leave blank to install a self-service site.
# Or enter the product you would like to build.
# If installing a product, you will need add the Environment Variable
# ACCESS_TOKEN, to the settings for this repository at travis-ci.org.
# The toggle "Display value in build log" should be off before clicking Add.
# Options include
# - jumpstart
# - jumpstart-plus
# - jumpstart-lab
# - jumpstart-academic
# - jumpstart-engineering
#
# ENABLE_MODULES:
# Enter as a space separated string, modules and submodules that you
# would like to enable after the installation profile has run. Useful
# for adding additional items. You do not need to include the module
# being tested. You can include a specific module version or stanford
# module branch name.
# Example:
# stanford_gallery-7.x-2.x nobots-7.x-1.x-dev stanford_page
#
# DISABLE_MODULES:
# Enter as a space separated string, modules you would like disabled after the
# installation profile has run.
# Example:
# webauth webauth_extras
#
# ONLY_TEST:
# This is an experimental feature for make files. So that we can test deployer
# and Drupal Profile builds.
# Example:
# field_collection
#
# DEPLOYER_BRANCH:
# Leave blank to use the default stanford-jumpstart-deployer branch.
# Example:
# basic-1234
#
# DRUPAL_PROFILE_BRANCH:
# Leave blank to use the default Stanford-Drupal-Profile branch.
#
# CLICKY_BRANCH:
# Leave blank to use the default linky_clicky branch.
# Example:
# 4.x
#
# SCRIPTS_BRANCH:
# Leave blank to use the default stanford_travisci_scripts branch.
# Example:
# HSDO-709-landing-page

env:
  global:
    - PRODUCT_NAME=""
    - ENABLE_MODULES="uuid stanford_ssp stanford_person stanford_capx capx_auto_nodetitle capx_filters capx_issue_collector capx_ssp capx_tamper capx_webauth"
    - DISABLE_MODULES=""
    - ONLY_TEST=""
    - DEPLOYER_BRANCH=""
    - DRUPAL_PROFILE_BRANCH=""
    - CLICKY_BRANCH=""
    - SCRIPTS_BRANCH=""

language: php
php:
  - '5.6'

sudo: required
dist: precise

cache:
  directories:
    - $HOME/.cache
    - $HOME/.composer/cache
    - $HOME/.drush/cache

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  # download external repository with Stanford Travis CI scripts
  - if [ ! -z $SCRIPTS_BRANCH ]; then SCRIPTS_BRANCH="-b $SCRIPTS_BRANCH"; fi
  - git clone $SCRIPTS_BRANCH https://github.com/SU-SWS/stanford_travisci_scripts.git $HOME/stanford_travisci_scripts
  - chmod +x $HOME/stanford_travisci_scripts/bin/*.sh
  # install composer packages
  - $HOME/stanford_travisci_scripts/bin/before_install.sh

install:
  # install self-service site, disable webauth module, start webserver and selenium webdriver
  - $HOME/stanford_travisci_scripts/bin/install.sh

before_script:
  # download linky_clicky, grab related tests, and start xvfb virtual display
  - $HOME/stanford_travisci_scripts/bin/before_script.sh

script:
  # make sure shell can find drush and run behat tests here, so Travis CI reports accurate results
  - $HOME/stanford_travisci_scripts/bin/script.sh
